Embedcolor on market and auction infos
poketwo/poketwo pull request #262
Opened 2021-07-19 21:12 UTC by WitherredAway

Would this work for the FR #261 ?

2021-07-20 04:14 UTC, oliver-ni requested changes

2021-07-20 04:14 UTC, oliver-ni commented on cogs/auctions.py
> +        embed = self.bot.Embed(color=pokemon.color or helpers.constants.PINK)
```suggestion
        embed = self.bot.Embed(color=pokemon.color or constants.PINK)
```

2021-07-20 04:14 UTC, oliver-ni commented on cogs/market.py
> +        embed = self.bot.Embed(color=pokemon.color or helpers.constants.PINK)
```suggestion
        embed = self.bot.Embed(color=pokemon.color or constants.PINK)
```

2021-07-20 04:19 UTC, WitherredAway commented
Added requested fixes

2021-07-21 18:49 UTC, oliver-ni approved these changes
lgtm

2021-07-21 18:49 UTC, merged