fix issues with auctions ending before you finish bidding
poketwo/poketwo pull request #269
Opened 2021-07-23 15:55 UTC by pikaninja

This pr replaces the` asyncio.Semaphore(1)`(which is actually the same as an asyncio.Lock) an defaultdict of asyncio.Locks, which will use the guild id as the key.

This is good once auctions is released to multiple guilds, since auctions from different guilds shouldn't conflict.

This pr also adds a lock to the ending auction process, which should fix issues with you losing money but not winning the auction.

2021-07-23 16:08 UTC, oliver-ni requested changes
Will test later.

2021-07-23 16:08 UTC, oliver-ni commented on cogs/auctions.py
> +import collections
```suggestion
from collections import defaultdict
```

2021-07-23 16:08 UTC, oliver-ni commented on cogs/auctions.py
> +        self.locks = collections.defaultdict(asyncio.Lock)
```suggestion
        self.locks = defaultdict(asyncio.Lock)
```

2021-07-23 16:10 UTC, NCPlayz approved these changes
code seems fine to me.

2021-08-15 21:08 UTC, oliver-ni approved these changes

2021-08-15 21:08 UTC, merged

2021-10-17 04:24 UTC, WitherredAway commented
This bug is still persisting unfortunately :(