Fix art credits
poketwo/poketwo pull request #548
Opened 2023-09-22 10:54 UTC by WitherredAway

- Fixed art credits for 550289905079812106 (Lights Pyukumuku) and 745825974880436294 (Choco Milcery, Lights Pyukumuku, Egg Basket Buneary)
- Multi art credits now go more into detail about the role of the users

2023-09-23 22:21 UTC, oliver-ni requested changes
Looks good, but can we not use | in the art credits? And maybe change the word "idea" to "concept"

Like "Artwork by ID • Concept by ID"

2025-08-03 13:02 UTC, quencs approved these changes

2025-08-05 03:13 UTC, closed without merging

2025-08-05 10:56 UTC, quencs reviewed
-

2025-08-05 19:18 UTC, quencs reviewed
****